service: chomp-btc-poc
useDotenv: true
plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs12.x
 apiGateway: {
    shouldStartNameWithService: true
  }
 lambdaHashingVersion: 20201221

functions:
 main: 
    handler: src/lambda.handler
    events:
     - http:
         method: any
         path: /{any+}

package:
  individually: true
  patterns:
    - '.env**'         